version: "3.8"

services:
  simple-sum:
    image: ozteps/simple-sum:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 32M
    ports:
      - "9001:80"

  blink:
    image: ozteps/blink:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 32M
    ports:
      - "9002:80"

  blink-api:
    image: ozteps/blink-api:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 128M
    ports:
      - "8002:8080"
    environment:
      - DATABASE=mongodb+srv://jcabral:9wmPRPKXdgqcHqI6@cluster0.s9efpek.mongodb.net/blink?retryWrites=true&w=majority&appName=Cluster0

  cryptlink:
    image: ozteps/cryptlink:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 32M
    ports:
      - "9003:80"

  cryptlink-api:
    image: ozteps/cryptlink-api:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 96M
    ports:
      - "8003:8080"
    environment:
      - DATABASE=mongodb+srv://jcabral:9wmPRPKXdgqcHqI6@cluster0.s9efpek.mongodb.net/cryptlink
      - DATABASE_NAME=secret-links

  cardsage-api:
    image: ozteps/cardsage-api:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          memory: 256M
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=sk-proj-opvmxhWIIy06oQKNyFMmT3BlbkFJsIz9bO8GMceCSfDf2CQV # Verifique a segurança das credenciais
      - PROJECT_ID=proj_noaKqfJadDzcwlpdr40412HS
      - ORGANIZATION=org-25YcHj5xoRloJDcgpLoZAAoy
      - DBHOST=mongodb+srv://jcabral:9wmPRPKXdgqcHqI6@cluster0.s9efpek.mongodb.net/blink?retryWrites=true&w=majority&appName=Cluster0
      - DATABASE=CardSage
      - COLLECTION=catalogo-de-links
      - JWT_SECRET_KEY=AKcu9@bP@W6v%x&g57bKQ^P7XXJ52M9oMqC
      - SECRET_KEY=e2g&Csy*82iHEJyXPHCattPXmEgKTpS%^X%
      - JWT_ACCESS_TOKEN_EXPIRES=30
      - REDIS_URL=redis://default:9yooZeAMooRTsnvMoW6teUpMyoBt1rVd@redis-10663.c308.sa-east-1-1.ec2.redns.redis-cloud.com:10663
      - MODE=production
      - TAGLIST=Inovação,Games,Filmes,Séries,Animes,Notícias,Desenvolvimento,Festas,Cursos,Saúde,Educação,Ciência,RedesSociais,Música,Livros,Moda,Culinária,Viagens,Arte,Promoções

  db_mysql:
    image: mysql:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
    environment:
      MYSQL_ROOT_PASSWORD: ozteps # Verifique a segurança das credenciais
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin # Verifique a segurança das credenciais
    ports:
      - "3306:3306"
    volumes:
      - banco_relacional:/var/lib/mysql
      - /etc/letsencrypt/live/mysql.abelcode.dev/fullchain.pem:/etc/mysql/ssl/fullchain.pem
      - /etc/letsencrypt/live/mysql.abelcode.dev/privkey.pem:/etc/mysql/ssl/privkey.pem
    networks:
      - abel_network

  phpmyadmin:
    image: phpmyadmin:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
    environment:
      PMA_HOST: db_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 9004:80
    depends_on:
      - db_mysql
    networks:
      - abel_network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup

volumes:
  banco_relacional:
    driver: local

networks:
  abel_network:
    driver: overlay
    attachable: true
